version: 1.0.{build}
configuration: Release
platform: Any CPU
build_script:
- cmd: >-
    dotnet restore .\

    dotnet build .\

    dotnet pack .\
artifacts:
- path: '**\*.nupkg'
  name: Nuget
deploy:
- provider: NuGet
  api_key:
    secure: hgfGc8iw8D2vcsl0AGUlHJNweZl9CbPxjROnuQYfa+rxDb4DTpBWJ0hkGsNesaiK
  artifact: /.*\.nupkg/